name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions:
  contents: write

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
